#!/bin/sh
# Sucleave_test1 - for program SUCLEAVE
# Author: Andre Latour, Feb 2022
#
  echo " "
  echo "-- Make null traces, set offset to centre of ranges. Use absolute. ---"
  echo " "
#
  sunull nt=100 ntr=5 >tnull11.su
  sushw <tnull11.su >tnull12.su key=offset a=-250 b=100
  sugethw <tnull12.su key=offset
#
  sucleave <tnull12.su key=offset low=50 size=100 high=250 print=1
#
  echo " "
  echo " Print offsets from one of the output files: cleave_offset_50.su "
  echo " Note that its file name indicates its offset range.             "
  echo " "
  sugethw <cleave_offset_50.su key=offset
#
