#!/bin/sh
# Sucleave_test3 - for program SUCLEAVE
# Author: Andre Latour, Feb 2022
#
  echo " "
  echo "-- Make null traces with some offsets out-of-range. Use absolute ---"
  echo "-- No print option (still warns about out-of-range).             ---"
  echo " "
#
  sunull nt=100 ntr=10 >tnull31.su
  sushw <tnull31.su >tnull32.su key=offset a=-450 b=100
  sugethw <tnull32.su key=offset
#
  sucleave <tnull32.su key=offset low=50 size=100 high=250 
#
  echo " "
  echo " Print offsets from the extra out-of-range (high) file.            "
  echo " "
  sugethw <cleave_offset_350.su key=offset
#
