#! /bin/sh


#  Default example
# x is the population:
    verhulst a1=1.0 a2=2000 h=0.01 stepmax=2000 mode=x |
       xgraph n=2000 nplot=1 d1=0.01 style=normal &
# y is dx/dt, the rate of growth of the population:
    verhulst a1=1.0 a2=2000 h=0.01 stepmax=2000 mode=y |
       xgraph n=2000 nplot=1 d1=0.01 style=normal &
# show both:
    verhulst a1=1.0 a2=2000 h=0.01 stepmax=2000 mode=x > population.bin
    verhulst a1=1.0 a2=2000 h=0.01 stepmax=2000 mode=y > rate.bin

 cat population.bin rate.bin |
     xgraph n=2000 nplot=2 d1=.01 style=normal &

exit 0
