#!/bin/sh
# Sushiftcsv_test1 - for program SUSHIFTCSV
# Author: Andre Latour, Aug 2023
#
  echo "----------------------------------------------------------------------------"
  echo "---  Input fake traces, apply shifts.                                       "
  echo "---  Basic test of computing/applying shifts (reverse and then forward).    "
  echo "----------------------------------------------------------------------------"
#
  suxwigb <fake04.su title=" before shifts " &
#
  sunszonecsv <fake04.su >fake11.su              locs=0 tpath=0 tapp=1 apply=1  \
              qin=l2scrookred.csv
#
  sugethw <fake11.su key=sx,sy,selev,sdepth,gx,gy,gelev,offset,sstat,gstat,tstat,sec
#
  suxwigb <fake11.su title=" after apply=1 shift " &
#
  sunszonecsv <fake11.su >fake12.su              locs=0 tpath=0 tapp=1 apply=-1   \
              qin=l2scrookred.csv
#
  suxwigb <fake12.su title=" after apply=1 and apply=-1 shifts " &
#
