#!/bin/sh
# Sushiftcsv_test1 - for program SUSHIFTCSV
# Author: Andre Latour, Aug 2023
#
  echo "----------------------------------------------------------------------------"
  echo "---  Input fake traces, apply shift.                                        "
  echo "---  In this test, the l2scrookred2 file has station 161 instead of 141 and "
  echo "---  the fourth velocity at 161 is 3300 rather than 3000.                   "
  echo "---  This allows you to compute what the tstat key value shift should be    "
  echo "---  and compare it to the results. Other layer velocities can be changed   "
  echo "---  in the l2scrookred2 file as well.                                      "
  echo "---  As well, this setup adds 120 to the shot depth so you can manually     "
  echo "---  compute the results and compare to the result from sunszonecsv.        "
  echo "----------------------------------------------------------------------------"
#
# Note suchw does not honour scalco or scalel. So sdepth 120 means 12 for these headers.
#
  suchw <fake04.su >fake21.su key1=gelev,sdepth key2=selev,sdepth key3=selev,sdepth a=0,120
#
  sunszonecsv <fake21.su >fake22.su              locs=0 tpath=0 tapp=1 apply=1   \
              qin=l2scrookred2.csv
#
  sugethw <fake22.su key=sx,sy,selev,sdepth,gx,gy,gelev,offset,sstat,gstat,tstat,sec
#
  suxwigb <fake22.su title=" after shifts " &
#
