#!/bin/sh
# Sushiftcsv_test1 - for program SUSHIFTCSV
# Author: Andre Latour, Aug 2023
#
  echo "----------------------------------------------------------------------------"
  echo "---  Input fake traces, apply shift.                                        "
  echo "---  The l2scrookred4 file has different names for the columns.             "
  echo "---  This allows testing of the parameters which specify the names.         "
  echo "----------------------------------------------------------------------------"
#
# Note suchw does not honour scalco or scalel. So sdepth 120 means 12 for these headers.
#
  suchw <fake04.su >fake41.su key1=gelev,sdepth key2=selev,sdepth key3=selev,sdepth a=0,120
#
  sunszonecsv <fake41.su >fake42.su              locs=0 tpath=0 tapp=1 apply=1 \
              qx=skkx qy=sandrey qvw=vaw qzw=zbbw_true qvb=vnnnb qzb=zbbw_true \
              qvc=vwwwc qzc=zccc_true qvd=vddd \
              qin=l2scrookred4.csv
#
  sugethw <fake42.su key=sx,sy,selev,sdepth,gx,gy,gelev,offset,sstat,gstat,tstat,sec
#
  suxwigb <fake42.su title=" after shift " &
#
