#!/bin/sh
# Sunearcsv_test2 - for program SUNEARCSV
# Author: Andre Latour, Oct  2022
#
  echo "----------------------------------------------------------------------------"
  echo "---  This test is similar to test1 except the generated sx,sy and gx,gy     "
  echo "---  values are symmetrically deviated in opposite directions from the      "
  echo "---  XYs of test1. This means the trace shot XYs and receiver XYs are       "
  echo "---  different from test1, but the trace midpoint XYs are the same as test1 "
  echo "---  (the traces would NOT have offset=0 if offset was computed).           "
  echo "---                                                                         "
  echo "---  Note that, like test1, sunearcsv uses the dimx=mgx dimy=mgy options,   "
  echo "---  which computes the midpoint XYs from the trace sx,sy,gx,gy but then    "
  echo "---  searches for the nearest gx,gy values in the qin file.                 "
  echo "---                                                                         "
  echo "---  This test should produce same cdp,igi,igc values as test1 (and does).  "
  echo "----------------------------------------------------------------------------"
#
 suprofcsv keyx=gx keyy=gy keyp=asis gx=0,1000,1000 gy=0,0,1500 \
           chordi=100 nmaxa=3 nmaxs=3 chordf=100 \
           qout=testout21.csv
#
 sunull nt=4 ntr=10 >tnull21.su
#sushw <tnull21.su >tnull22.su key=sx,sy,gx,gy a=600,-50,600,-50 b=60,125,60,125
 sushw <tnull21.su >tnull22.su key=sx,sy,gx,gy a=700,-30,500,-70 b=60,125,60,125
#
 sunearcsv qin=testout21.csv <tnull22.su dimx=mgx dimy=mgy >tnear21.su keyp=cdp okeys=cdp
#
 suchw <tnear21.su >tnear22.su key1=sdel,gdel key2=sx,sy key3=gx,gy b=1,1 c=1,1 d=2,2 
 sugethw <tnear22.su key=sx,sy,gx,gy,sdel,gdel,cdp,igi,igc
#
# Use sed to remove the first lines (C_SU header lines).
# Use cut with a deliminator of comma to retain only fields 3 and 4
# Use sed to replace every comma with a blank.               
# Use a2b to convert ascii to binary                        
# Use sugethw to output x,y values in binary.                                   
# Use cat to combine the 2 sets of XYs into one file.                           
#
# Use xgraph to plot 2 sets of points with marks of Xs and triangles.
#
 sed '/C_SU/d' testout21.csv >testout22.csv
 cut -d, -f3,4 <testout22.csv >testout23.csv
 sed '1,$ s/,/ /g' testout23.csv >testout23.txt
 a2b <testout23.txt >testout23.bin
#
 sugethw <tnear22.su output=binary key=sdel,gdel >testout24.bin
 cat testout23.bin testout24.bin >testout25.bin
#
 xgraph <testout25.bin n=40,10 linecolor=2,3 mark=2,6 marksize=10,10 linewidth=0 \
         width=1000 height=700 x1beg=-800 x1end=1400 x2beg=-100 x2end=2800
