#!/bin/sh
# Sunearcsv_test5 - for program SUNEARCSV
# Author: Andre Latour, Oct  2022
#
  echo "----------------------------------------------------------------------------"
  echo "---  This test is similar to test4 except the generated sx,sy and gx,gy     "
  echo "---  values are symmetrically deviated in opposite directions from the      "
  echo "---  XYs of test4. This means the trace shot XYs and receiver XYs are       "
  echo "---  different from test4, but the trace midpoint XYs are the same as test4 "
  echo "---  (the traces would NOT have offset=0 if offset was computed).           "
  echo "---                                                                         "
  echo "---  Note that, like test4, suprofcsv creates a profile with sx,sy names.   "
  echo "---                                                                         "
  echo "---  So, also like test4, sunearcsv uses the dimx=msx dimy=msy options,     "
  echo "---  which computes the midpoint XYs from the trace sx,sy,gx,gy but then    "
  echo "---  searches for the nearest sx,sy values in the qin file.                 "
  echo "---                                                                         "
  echo "---  This test should produce same cdp,igi,igc values as test1 (and does).  "
  echo "----------------------------------------------------------------------------"
#
 suprofcsv keyx=sx keyy=sy keyp=asis sx=0,1000,1000 sy=0,0,1500 \
           chordi=100 nmaxa=3 nmaxs=3 chordf=100 \
           qout=testout51.csv
#
 sunull nt=4 ntr=10 >tnull51.su
 sushw <tnull51.su >tnull52.su key=sx,sy,gx,gy a=700,-30,500,-70 b=60,125,60,125
#
 sunearcsv qin=testout51.csv <tnull52.su dimx=msx dimy=msy >tnear51.su keyp=cdp okeys=cdp
#
 suchw <tnear51.su >tnear52.su key1=sdel,gdel key2=sx,sy key3=gx,gy b=1,1 c=1,1 d=2,2 
 sugethw <tnear52.su key=sx,sy,gx,gy,sdel,gdel,cdp,igi,igc
#
# Use sed to remove the first lines (C_SU header lines).
# Use cut with a deliminator of comma to retain only fields 3 and 4
# Use sed to replace every comma with a blank.               
# Use a2b to convert ascii to binary                        
# Use sugethw to output x,y values in binary.                                   
# Use cat to combine the 2 sets of XYs into one file.                           
#
# Use xgraph to plot 2 sets of points with marks of Xs and triangles.
#
 sed '/C_SU/d' testout51.csv >testout52.csv
 cut -d, -f3,4 <testout52.csv >testout53.csv
 sed '1,$ s/,/ /g' testout53.csv >testout53.txt
 a2b <testout53.txt >testout53.bin
#
 sugethw <tnear52.su output=binary key=sdel,gdel >testout54.bin
 cat testout53.bin testout54.bin >testout55.bin
#
 xgraph <testout55.bin n=40,10 linecolor=2,3 mark=2,6 marksize=10,10 linewidth=0 \
         width=1000 height=700 x1beg=-800 x1end=1400 x2beg=-100 x2end=2800
