#!/bin/sh
# Sunearcsv_test3 - for program SUNEARCSV
# Author: Andre Latour, Oct  2022
#
  echo "----------------------------------------------------------------------------"
  echo "---  This test is similar to test1 (sx=gx and sy=gy).                       "
  echo "---                                                                         "
  echo "---  But unlike test1, sunearcsv herein uses the dimx=gx dimy=gy options,   "
  echo "---  which uses the trace gx,gy values and searches for the                 "
  echo "---  nearest gx,gy values in the qin file.                                  "
  echo "---                                                                         "
  echo "---  Since sx=gx and sy=gy                                                  "
  echo "---  this test should produce same cdp,igi,igc values as test1 (and does).  "
  echo "----------------------------------------------------------------------------"
#
 suprofcsv keyx=gx keyy=gy keyp=asis gx=0,1000,1000 gy=0,0,1500 \
           chordi=100 nmaxa=3 nmaxs=3 chordf=100 \
           qout=testout31.csv
#
 sunull nt=4 ntr=10 >tnull31.su
 sushw <tnull31.su >tnull32.su key=sx,sy,gx,gy a=600,-50,600,-50 b=60,125,60,125
#
 sunearcsv qin=testout31.csv <tnull32.su dimx=gx dimy=gy >tnear31.su keyp=cdp okeys=cdp
#
 suchw <tnear31.su >tnear32.su key1=sdel,gdel key2=sx,sy key3=gx,gy b=1,1 c=1,1 d=2,2 
 sugethw <tnear32.su key=sx,sy,gx,gy,sdel,gdel,cdp,igi,igc
#
# Use sed to remove the first lines (C_SU header lines).
# Use cut with a deliminator of comma to retain only fields 3 and 4
# Use sed to replace every comma with a blank.               
# Use a2b to convert ascii to binary                        
# Use sugethw to output x,y values in binary.                                   
# Use cat to combine the 2 sets of XYs into one file.                           
#
# Use xgraph to plot 2 sets of points with marks of Xs and triangles.
#
 sed '/C_SU/d' testout31.csv >testout32.csv
 cut -d, -f3,4 <testout32.csv >testout33.csv
 sed '1,$ s/,/ /g' testout33.csv >testout33.txt
 a2b <testout33.txt >testout33.bin
#
 sugethw <tnear32.su output=binary key=sdel,gdel >testout34.bin
 cat testout33.bin testout34.bin >testout35.bin
#
 xgraph <testout35.bin n=40,10 linecolor=2,3 mark=2,6 marksize=10,10 linewidth=0 \
         width=1000 height=700 x1beg=-800 x1end=1400 x2beg=-100 x2end=2800
