#!/bin/sh
# Sunearcsv_test6 - for program SUNEARCSV
# Author: Andre Latour, Oct  2022
#
  echo "----------------------------------------------------------------------------"
  echo "---  Similar to test1 except generating a receiver station number (gaps)    "
  echo "---  during definition of the profile and using it to sort that profile.    "
  echo "---                                                                         "
  echo "---  Note that gaps comes out first on q-records (before gx and gy), which  "
  echo "---  requires an adjustment of the fields that cut retains.                 "
  echo "---                                                                         "
  echo "----------------------------------------------------------------------------"
#
 suprofcsv keyx=gx keyy=gy keyp=gaps gx=0,1000,1000 gy=0,0,1500 gaps=200,300,500 \
           chordi=100 nmaxa=3 nmaxs=3 chordf=100 \
           qout=testout61.csv
#
 sunull nt=4 ntr=10 >tnull61.su
 sushw <tnull61.su >tnull62.su key=sx,sy,gx,gy a=600,-50,600,-50 b=60,125,60,125
#
 sunearcsv qin=testout61.csv <tnull62.su dimx=mgx dimy=mgy >tnear61.su keyp=cdp okeys=cdp,gaps
#
 suchw <tnear61.su >tnear62.su key1=sdel,gdel key2=sx,sy key3=gx,gy b=1,1 c=1,1 d=2,2 
 sugethw <tnear62.su key=sx,sy,gx,gy,sdel,gdel,gaps,cdp,igi,igc
#
# Use sed to remove the first lines (C_SU header lines).
# Use cut with a deliminator of comma to retain only fields 3 and 4
# Use sed to replace every comma with a blank.               
# Use a2b to convert ascii to binary                        
# Use sugethw to output x,y values in binary.                                   
# Use cat to combine the 2 sets of XYs into one file.                           
#
# Use xgraph to plot 2 sets of points with marks of Xs and triangles.
#
 sed '/C_SU/d' testout61.csv >testout62.csv
 cut -d, -f4,5 <testout62.csv >testout63.csv
 sed '1,$ s/,/ /g' testout63.csv >testout63.txt
 a2b <testout63.txt >testout63.bin
#
 sugethw <tnear62.su output=binary key=sdel,gdel >testout64.bin
 cat testout63.bin testout64.bin >testout65.bin
#
 xgraph <testout65.bin n=40,10 linecolor=2,3 mark=2,6 marksize=10,10 linewidth=0 \
         width=1000 height=700 x1beg=-800 x1end=1400 x2beg=-100 x2end=2800
