#!/bin/sh
# Sumatrix_create_simple3d - for program SUMATRIX
# Author: Andre Latour, Aug 2024
#
  echo "----------------------------------------------------------------------------"
  echo "---  Use sugeomcsv to create traces with simple 3D geometry.                "
  echo "---  See demos/Geom3D/Sugeomcsv for how this is done.                       "
  echo "----------------------------------------------------------------------------"
#
  sugeomcsv rfile=l2xall.txt >fake31.su setid=x names=sps2 match=sps2 \
            create=all spikes=4,0.01,220,1000,228,-1200,1000,0
#
  sugeomcsv rfile=l2sall.txt <fake31.su >fake32.su setid=s names=sps2 match=sps2 
#
  sugeomcsv rfile=l2rall.txt <fake32.su >fake33.su setid=r names=sps2 match=sps2
#
  subfilt <fake33.su >fake34.su fpasshi=20
#
  sustatic <fake34.su >fake35.su hdrs=1 sign=-1
#
  suchw <fake35.su >fake36.su key1=sstat,gstat,tstat key2=sstat,offset,tstat key3=sstat,gstat,tstat a=0,0,0 b=0,0.09,0 c=0,0,0
#
  sustatic <fake36.su >fake37.su hdrs=1 sign=-1
#
  suxwigb <fake37.su title="flatish" &
#
