#!/bin/sh
# Sugeomcsp_input_realistic - for program SUGEOMCSV
# Author: Andre Latour, July 2021
#
  echo "----------------------------------------------------------------------------"
  echo "---  sugeomcsv updates SU trace headers from fixed-format or csv files.     "
  echo "---  For initial geometry from SPS2 files, 3 runs of sugeomcsv are required."
  echo "                                                                            "
  echo "---  ... You should run your SPS2 files through SUTOOLCSV before this...    "
  echo "                                                                            "
  echo "---  The idea of this example is to show novice users how to proceed.       "
  echo "                                                                            "
  echo "     I suggest you start by viewing files shots.png and receiver.png        "
  echo "     which show the locations of shot and receiver lines and points         "
  echo "     of the 3D land survey contained in the input SPS2 files.               "
  echo "----------------------------------------------------------------------------"
#
  sugeomcsv rfile=l2xall.txt setid=x match=sps2 names=sps2 <fakeall.su >fakeallx.su
#
  echo " --- that was first run of sugeomcsv ---"
#
  sugeomcsv rfile=l2sall.txt setid=s match=sps2 names=sps2 <fakeallx.su >fakeallxs.su
# rm -f fakeallx.su 
#
  echo " --- that was second run of sugeomcsv ---"
#
  sugeomcsv rfile=l2rall.txt setid=r match=sps2 names=sps2 <fakeallxs.su >fakeallxsr.su
# rm -f fakeallxs.su 
#
  echo " --- that was third run of sugeomcsv ---"
#
  sunmo <fakeallxsr.su >fakeallxsrn.su tnmo=0,190,450,800 vnmo=1800,3500,4000,5000
# rm -f fakeallxsr.su 
#
  echo " --- applying forward nmo and displaying ---"
#
#--------
#
  suximage <fakeallxsrn.su
#
  echo "                                                                            "
  echo "                                                                            "
  echo "----------------------------------------------------------------------------"
  echo "---  sugeomcsv updates SU trace headers from fixed-format or csv files.     "
  echo "---  For initial geometry from SPS2 files, 3 runs of sugeomcsv are required."
  echo "                                                                            "
  echo "---  ... You should run your SPS2 files through SUTOOLCSV before this...    "
  echo "                                                                            "
  echo "---  The idea of this example is to show novice users how to proceed.       "
  echo "                                                                            "
  echo "     I suggest you start by viewing files shots.png and receiver.png        "
  echo "     which show the locations of shot and receiver lines and points         "
  echo "     of the 3D land survey contained in the input SPS2 files.               "
  echo "----------------------------------------------------------------------------"
