#!/bin/sh
# Sufarldcsv_2d_test0 - for program SUFARLDCSV
# Author: Andre Latour, Nov 2023
#
  echo "----------------------------------------------------------------------------"
  echo " Input l2rlongcutends.csv to suprofcsv to produce the cdp q-file locations. "
  echo "   Note suprofcsv has a special setup here. This setup generates a profile  "
  echo "   with the same cdp numbers computed and updated to traces by subincsv     "
  echo "   (as long as you also use the same point_crz and point_cru values here).  "
  echo "   Note that nmaxa=0 (no profile smoothing wanted in this case).            "
  echo "   Note dextra=20 to extrapolate extra cdps just in case some shots exist   "
  echo "   beyond receiver extent.                                                  "
  echo " But, if you have used suprofcsv to create a (crooked or straight) profile  "
  echo " and then used sunearcsv to update the trace cdp nuumbers, then THAT        "
  echo " profile should be used as the cin file in sufaldcsv.                       "
  echo "                                                                            "
  echo " Then run sufarldcsv:                                                       "
  echo "   Input l2slongcut2.csv which contains sections of missing shots.          "
  echo "   Input l2rlongcutends.csv which contains missing receivers on ends.       "
  echo "   Input l2plong01.csv which contains the cdp locations made above.         "
  echo "                                                                            "
  echo " *** These are the same input files as used by test9.                       "
  echo " *** But note that sloc,rloc,cloc are using their station numbers, not XYs. "
  echo " *** The avrad is set to 50 rather than default 1000 since these stations   "
  echo " *** happend to be 20 metres (or feet) apart.                               "
  echo "                                                                            "
  echo "----------------------------------------------------------------------------"
#
  suprofcsv qin=l2rlongcutends.csv keyp=gaps keyx=gaps keyy=none \
            chordi=0.5 point_crz=1 point_cru=2 nmaxa=0 dextra=20. qout=l2plong01.csv  
#
# Input shot file with missing shots and receiver file with missing receivers.  
#
  sufarldcsv sin=l2slongcut2.csv sloc=grnlof \
             rin=l2rlongcutends.csv rloc=gaps \
             cin=l2plong01.csv cloc=gaps cseq=cdp  avrad=50              dout=testout01.csv   
#            cin=l2plong01.csv cloc=gaps cseq=cdp avrad=-1 navrg=2 nsmth=0 formxy=%.10g  
#
# Use sed to remove the first lines (C_SU header lines).
# Use cut with a deliminator of comma to retain only fields 2 and 5,6,7
# Use sed to replace every comma with a blank.               
# Use a2b to convert ascii to binary                        
# Use cat                                                   
# Use xgraph to plot points with marks of X, and no lines between.
#
  sed '/C_SU/d' testout01.csv >testout02.csv
#
  cut -d, -f2,5 <testout02.csv >testout03.csv
  sed '1,$ s/,/ /g' testout03.csv >testout03.txt
  a2b <testout03.txt >testout03.bin
#
  cut -d, -f2,6 <testout02.csv >testout04.csv
  sed '1,$ s/,/ /g' testout04.csv >testout04.txt
  a2b <testout04.txt >testout04.bin
#
  cut -d, -f2,7 <testout02.csv >testout05.csv
  sed '1,$ s/,/ /g' testout05.csv >testout05.txt
  a2b <testout05.txt >testout05.bin
#
  cat testout03.bin testout04.bin testout05.bin >testout06.bin 
#
  xgraph <testout06.bin nplot=3 n=841,841,841 linecolor=2,4,3 mark=1,6,7 marksize=5,5,5 linewidth=0 \
          style=normal width=1200 height=600 x1beg=0 x1end=1200 x2beg=-300 x2end=100 \
          title="averaged,smoothed shot,receiver,cdpdatum statics (red,blue,green) at cdp numbers with some missing shots,receivers USING STATION NUMBERS" & 
#
# Note the skeyloc and rkeyloc parameters. 
# Their defaults MAY be correct for 2Ds, but always need overrides for 3D.
#
  sushiftcsv <testouttraces2.su >testouttraces06.su \
              sin=l2slong.csv skeyloc=grnlof \
              rin=l2rlong.csv rkeyloc=gaps \
              cin=testout01.csv 
#
  suxwigb <testouttraces06.su title="traces after shifting by sushiftcsv (just a mechanical test)" &

