#!/bin/sh
# Sufarldcsv_3d_test7 - for program SUFARLDCSV
# Author: Andre Latour, Nov 2023
#
  echo "----------------------------------------------------------------------------"
  echo " Use subinxxcsv to enlarge and/or flip my usual grid definition in kEFG     "
  echo " If you change igilow (and so on), you must reset count (n=4731 in xgraph). "
  echo " Run sufarldcsv:                                                            "
  echo "   Input l2sall.csv which contains shot values.                             "
  echo "   Input l2rall.csv which contains receiver values.                         "
  echo " Display smoothed (shot+receiver)/2 values (usually statics or elevations). "
  echo "   Then apply statics using sushiftcsv. This is a mechanical test to        "
  echo "   see that the output q-file actually works as input to sushiftcsv.        "
  echo "                                                                            "
  echo " *** This test is initially set to same option values as tests 5,6.         "
  echo " *** But the displays are of the output (shot+receiver)/2 values.           "
  echo "                                                                            "
  echo " Note:                                                                      "
  echo "       The 3D Grid definition is deliberately enlarged to help see the      "
  echo "       affects of various options OUTSIDE the edges of shots and receivers. "
  echo " Note:                                                                      "
  echo "       l2rall.csv is all receivers with normal statics,elevations.          "
  echo "       l2rallr2.csv has 2 recrs with big diffs (line 100, points 102,150)   "
  echo "       l2rallr2l3.csv has 2 big diffs, and missing receivers on some lines  "
  echo "    *  l2sall.csv is all shots with normal statics,elevations.              "
  echo "    *  l2salll3.csv has missing shots near those missing receivers          "
  echo "       You can interchange those file names here without making other       "
  echo "       alterations in this script because the xgraph is of cdps (cells).    "
  echo " Note:                                                                      "
  echo "       Since a contour plot is produced, why plot the same values versus    "
  echo "       the cdp NUMBERS and transposed-cdp NUMBERS?                          "
  echo "        - because these are good ways to judge how well the inline cdp and  "
  echo "          crossline cdp averaging and smoothing options are working.        "
  echo "----------------------------------------------------------------------------"
#
  subinxxcsv rfile=kEFG.csv wfile=testgrid71.csv igilow=10 igchigh=8
#
# sufarldcsv sin=l2salll3.csv             rin=l2rallr2l3.csv         \
# sufarldcsv sin=l2sall.csv sstat=selev   rin=l2rall.csv rstat=gelev \
#
  sufarldcsv sin=l2sall.csv               rin=l2rall.csv             \
             rfile=testgrid71.csv                                              dout=testout71.csv   
#
#            rfile=testgrid71.csv avrad=1000 navrg=10,10 nsmth=10,10 nback=3,3 dout=testout71.csv   
#
# The options below result in outputting nearest values with no smoothing at all.
#                                 avrad=-1   navrg=0                          
#
# Use sed to remove the first lines (C_SU header lines).
# Use cut with a deliminator of comma to retain only fields 2 and 11
# Use sed to replace every comma with a blank.               
# Use a2b to convert ascii to binary                        
# Use xgraph to plot points with marks of X, and no lines between.
#
  sed '/C_SU/d' testout71.csv >testout72.csv
#
  cut -d, -f2,12 <testout72.csv >testout73.csv
  sed '1,$ s/,/ /g' testout73.csv >testout73.txt
  a2b <testout73.txt >testout73.bin
  xgraph <testout73.bin n=4371 linecolor=3 mark=7 marksize=5 linewidth=0 \
          style=normal width=1200 height=600 x1beg=-100 x1end=4500 x2beg=-200 x2end=200 \
          title=" (shot+receiver)/2 value at cdp NUMBERS " &
#
# Use cut with a deliminator of comma to retain only fields 3 and 11
#
  cut -d, -f3,12 <testout72.csv >testout74.csv
  sed '1,$ s/,/ /g' testout74.csv >testout74.txt
  a2b <testout74.txt >testout74.bin
  xgraph <testout74.bin n=4371 linecolor=3 mark=7 marksize=5 linewidth=0 \
          style=normal width=1200 height=600 x1beg=-100 x1end=4500 x2beg=-200 x2end=200 \
          title=" smoothed (shot+receiver)/2 value at transposed cdp NUMBERS " &
#
# Use cut with a deliminator of comma to retain only field 10 (smoothed shot static at cdp) red
#                                                          11 (smoothed receiver static at cdp) blue
#                                                          12 (smoothed (shot+rec) / 2  at cdp) green
# Use sed to replace every comma with a blank.               
# Use a2b to convert ascii to binary (note n1=1)                        
# Use xgraph to plot points with marks of X, and no lines between (note n1=141 inline cells)
#
  cut -d, -f12 <testout72.csv >testout75.csv
  sed '1,$ s/,/ /g' testout75.csv >testout75.txt
  a2b n1=1 <testout75.txt >testout75.bin
#
  xcontour n1=141 d1=25 d2=50 nc=20 wbox=600 hbox=700 ccolor=green <testout75.bin \
    title=" smoothed (shot+receiver)/2 value contoured    axes are inline,crossline distances " &
#
# Note the skeyloc and rkeyloc parameters. 
# Their defaults MAY be correct for 2Ds, but always need overrides for 3D.
#
  sushiftcsv <testouttraces2.su >testouttraces76.su \
              sin=l2sall.csv skeyloc=grnofr,grnlof \
              rin=l2rall.csv rkeyloc=grnors,gaps \
              cin=testout71.csv
#
  suxwigb <testouttraces76.su title="fake traces after shifting by default (TSTAT) as cdp datum static in sushiftcsv " &
#
