#!/bin/sh
# Sugeomcsp_create_simple2d - for program SUGEOMCSV
# Author: Andre Latour, July 2021
#
  echo "----------------------------------------------------------------------------"
  echo "---  The idea of this example is to create some realistic traces for 2D.    "
  echo "---  The sequence herein is:                                                "
  echo "---   - use l0xall.csv and create traces (do not bother making spikes)      "
  echo "---   - update X,Ys and other values from l0sall.csv and l0rall.csv files.  "
  echo "                                                                            "
  echo "      See Sutoolcsv/Sutoolcsp_simple2d for how to make simple 2d geometry   "
  echo "      files such as l0xall.csv, l0sall.csv, and l0rall.csv                  "
  echo "----------------------------------------------------------------------------"
#
  sugeomcsv rfile=l0xall.csv setid=x match=fldr,tracf names=c_su_id,match1,grnlof,matche1_cf,matche1_ct,matche1_ci,gaps_rf,gaps_rt >fake0x.su create=all 
#
  sugeomcsv rfile=l0sall.csv setid=s match=grnlof names=c_su_id,grnlof,sx,sy,selev <fake0x.su >fake0xs.su
# rm -f fakex.su 
#
  sugeomcsv rfile=l0rall.csv setid=r match=gaps names=c_su_id,gaps,gx,gy,gelev <fake0xs.su >fake0xsr.su
# rm -f fakexs.su 
#
  echo "                                                                            "
  echo "                                                                            "
  echo "----------------------------------------------------------------------------"
  echo "---  The idea of this example is to create some realistic traces for 2D.    "
  echo "---  The sequence herein is:                                                "
  echo "---   - use l0xall.csv and create traces (do not bother making spikes)      "
  echo "---   - update X,Ys and other values from l0sall.csv and l0rall.csv files.  "
  echo "                                                                            "
  echo "      See Sutoolcsv/Sutoolcsp_simple2d for how to make simple 2d geometry   "
  echo "      files such as l0xall.csv, l0sall.csv, and l0rall.csv                  "
  echo "----------------------------------------------------------------------------"
