#!/bin/sh
# Subincsp_example4 - for program SUBINCSV
# Author: Andre Latour, Aug 2021
#
  echo "----------------------------------------------------------------------------"
  echo "---  in this example, subincsv reads 2d points definition from command line "
  echo "---  parameters and updates cdp key.                                        "
  echo "----------------------------------------------------------------------------"
#
# Note that input traces were produced by demos/Geom3D/Sugeomcsv/Sugeomcsv_create_simple2d
#
  subincsv <fakeallxsrn.su >fakeallxsrnp.su bintype=20 point_crz=100 point_cru=2 point_csz=100 point_csu=2 wfile=k2.csv  
#
  sugethw <fakeallxsrnp.su key=offset,grnlof,gaps,cdp
