#!/bin/sh
# Surescsv_test5 - for program SURESCSV
# Author: Andre Latour, Aug 2023
#
  echo "----------------------------------------------------------------------------"
  echo "---  Create undulations across survey.                                      "
  echo "---  Deliberately use bad NMO velocities on second half of survey.          "
  echo "---  Use surescsv to derive statics.                                        "
  echo "---  Use sushiftcsv to apply those statics.                                 "
  echo "---  Make source,receiver,CDP stacks before and after.                      "
  echo "---  *** The actual affect of the bad NMO on the STATICS is quite subtle.   "
  echo "---      Note also that shot 40 and 120 have non-centred layouts.           "
  echo "---      The useoff and longwave parameters are most likely to be involved. "
  echo "----------------------------------------------------------------------------"
#
# Use selev,gelev to set sstat,gstat to produce undulations.         
# Remember to set tstat=0 as well since the previous sustatic set it, and next sustatic would use it.
#
  suchw <fake06.su >fake51.su key1=sstat,gstat,tstat key2=selev,gelev,cdp key3=sstat,gstat,gaps a=0,0,0 b=0.001,0.001,0 c=0,0,0
#
  sustatic <fake51.su >fake52.su hdrs=1
#
  sunmo <fake52.su >fake53.su invert=1 \
        cdp=1,370,371,740 \
        tnmo=0,0.190,0.450,0.800 \
        tnmo=0,0.190,0.450,0.800 \
        tnmo=0,0.190,0.450,0.800 \
        tnmo=0,0.190,0.450,0.800 \
        vnmo=1800,2500,4000,5000 \
        vnmo=1800,2500,4000,5000 \
        vnmo=1800,2500,4000,5000 \
        vnmo=1800,2500,4000,5000 
#
  sunmo <fake53.su >fake54.su          \
        cdp=1,370,371,740 \
        tnmo=0,0.190,0.450,0.800 \
        tnmo=0,0.190,0.450,0.800 \
        tnmo=0,0.190,0.450,0.800 \
        tnmo=0,0.190,0.450,0.800 \
        vnmo=1800,2500,4000,5000 \
        vnmo=1800,2500,4000,5000 \
        vnmo=1500,2000,3000,4000 \
        vnmo=1500,2000,3000,4000 
#
  suxwigb <fake54.su title="traces before surescsv" &
#
  sustackup <fake54.su >fake55.su keyloc=fldr
  suxwigb <fake55.su title="source stack before surescsv" &
#
  sustackup <fake54.su >fake56.su keyloc=gaps
  suxwigb <fake56.su title="receiver stack before surescsv" &
#
  sustackup <fake54.su >fake57.su keyloc=cdp
  suxwigb <fake57.su title="CDP stack before surescsv" &
#
# Here are some helpful hints for parameters to test.....
#
# surescsv <fake32.su maxsources=169 maxreceivers=397 maxcdps=733 maxtraces=10140
# surescsv <fake32.su cdivider=4.0 maxshift=40 numiter=5 useoff=1.5av iuseoff=0 longwave=av  srderive=0
# See the top of the sstat32.csv file for the actual defaulted values of useoff and longwave.                       
  surescsv <fake54.su sout=sstat54.csv rout=rstat54.csv
#
  sushiftcsv <fake54.su >fake55.su sin=sstat54.csv rin=rstat54.csv
#
  sustackup <fake55.su >fake56.su keyloc=fldr
  suxwigb <fake56.su title="source stack AFTER surescsv" &
#
  sustackup <fake55.su >fake57.su keyloc=gaps
  suxwigb <fake57.su title="receiver stack AFTER surescsv" &
#
  sustackup <fake55.su >fake58.su keyloc=cdp
  suxwigb <fake58.su title="CDP stack AFTER surescsv" &
#
