#!/bin/sh
# Surescsv_test2 - for program SURESCSV
# Author: Andre Latour, Aug 2023
#
  echo "----------------------------------------------------------------------------"
  echo "---  Use surescsv to derive statics.                                        "
  echo "---  Use sushiftcsv to apply those statics.                                 "
  echo "---  Make source,receiver,CDP stacks before and after.                      "
  echo "---  Note: This is test is for other location identifiers (sx,sy and gx,gy) "
  echo "---  Note: also tests override of output statics file names.                "
  echo "----------------------------------------------------------------------------"
#
  sustackup <fake06.su >fake21.su keyloc=fldr
  suxwigb <fake21.su title="source stack before surescsv" &
#
  sustackup <fake06.su >fake22.su keyloc=gaps
  suxwigb <fake22.su title="receiver stack before surescsv" &
#
  sustackup <fake06.su >fake23.su keyloc=cdp
  suxwigb <fake23.su title="CDP stack before surescsv" &
#
  surescsv <fake06.su sout=sstatxy.csv rout=rstatxy.csv skeyloc=sx,sy rkeyloc=gx,gy 
#
  sushiftcsv <fake06.su >fake25.su sin=sstatxy.csv rin=rstatxy.csv skeyloc=sx,sy rkeyloc=gx,gy
#
  sustackup <fake25.su >fake26.su keyloc=fldr
  suxwigb <fake26.su title="source stack AFTER surescsv" &
#
  sustackup <fake25.su >fake27.su keyloc=gaps
  suxwigb <fake27.su title="receiver stack AFTER surescsv" &
#
  sustackup <fake25.su >fake28.su keyloc=cdp
  suxwigb <fake28.su title="CDP stack AFTER surescsv" &
#
