#!/bin/sh
# Susembase_test5 - for program SUSEMBASE
# Author: Andre Latour, Feb 2023
#
  echo "----------------------------------------------------------------------------"
  echo "--- Test scan time range                                                 ---"
  echo "----------------------------------------------------------------------------"
#
 sugeomcsv rfile=cdps11.csv >tfake51a.su create=all spikes=4,0.00,100,2000,104,2400,108,1800,400,0 
 subfilt <tfake51a.su >tfake52a.su fpasshi=60
 suchw <tfake52a.su >tfake53a.su key1=gstat key2=tracf b=2
 sustatic <tfake53a.su >tfake54a.su hdrs=1 sign=-1
#
 sugeomcsv rfile=cdps11.csv >tfake51b.su create=all spikes=4,0.00,100,1200,104,2000,108,1600,400,0 
 subfilt <tfake51b.su >tfake52b.su fpasshi=40
 suchw <tfake52b.su >tfake53b.su key1=gstat key2=tracf b=-2 a=300
 sustatic <tfake53b.su >tfake54b.su hdrs=1 sign=-1
#
 suop2 tfake54a.su tfake54b.su op=sum >tfake54r.su
 suaddnoise <tfake54r.su >tfake54n.su sn=20 seed=1 
 suwind <tfake54n.su >tfake54.su key=cdp reject=21,22,23,24 
 suxwigb <tfake54.su key=cdp title="input " &
#
 susembase <tfake54.su >tfake55.su scanmax=8 scanmin=0          
#
 suxwigb <tfake55.su key=cdp title="output (note that scanmin=0 so the second horizon is bad)" &
#
