#!/bin/sh
# Susembase_test3 - for program SUSEMBASE
# Author: Andre Latour, Feb 2023
#
  echo "----------------------------------------------------------------------------"
  echo "--- Test using a reasonable (fake) cdp stack situation.                  ---"
  echo "---  - with 2 simple dipping horizons.                                   ---"
  echo "---  - removed cdps 21,22,23,24                                          ---"
  echo "---  - added noise                                                       ---"
  echo "---  - display input file                                                ---"
  echo "---  - Interpolate to half-cdps                                          ---"
  echo "---  - Also Interpolate to half-cdps but dipuse=0.                       ---"
  echo "----------------------------------------------------------------------------"
#
 sugeomcsv rfile=cdps11.csv >tfake31a.su create=all spikes=4,0.00,100,2000,104,2400,108,1800,400,0 
 subfilt <tfake31a.su >tfake32a.su fpasshi=60
 suchw <tfake32a.su >tfake33a.su key1=gstat key2=tracf b=2
 sustatic <tfake33a.su >tfake34a.su hdrs=1 sign=-1
#
 sugeomcsv rfile=cdps11.csv >tfake31b.su create=all spikes=4,0.00,100,1200,104,2000,108,1600,400,0 
 subfilt <tfake31b.su >tfake32b.su fpasshi=40
 suchw <tfake32b.su >tfake33b.su key1=gstat key2=tracf b=-2 a=300
 sustatic <tfake33b.su >tfake34b.su hdrs=1 sign=-1
#
 suop2 tfake34a.su tfake34b.su op=sum >tfake34r.su
 suaddnoise <tfake34r.su >tfake34n.su sn=5 seed=1 
 suwind <tfake34n.su >tfake34.su key=cdp reject=21,22,23,24
 suxwigb <tfake34.su key=cdp title="input " &
#
 susembase <tfake34.su >tfake35.su outputinc=0.5 
 suxwigb <tfake35.su key=cdp title="output (interpolated to 0.5 cdps)" &
#
 susembase <tfake34.su >tfake36.su outputinc=0.5 dipuse=0 
 suxwigb <tfake36.su key=cdp title="output (interpolated to 0.5 cdps ALSO   BUT dipuse=0)" &
#
