#!/bin/sh
# Supadmissing_test4 - for program SUPADMISSING
# Author: Andre Latour, Feb 2024
#
  echo "----------------------------------------------------------------------------"
  echo "---  Same traces created as for test1.                                      "
  echo "---  This test creates traces with simple cdp numbers (using sugeomcsv).    "
  echo "---  And a spike on all traces, which is filtered so it becomes a wavelet.  "
  echo "---  Those wavelets are shifted in time by an amount corresponding to cdp.  "
  echo "---  Those traces are then displayed.                                       "
  echo "---  Some of those traces are then deleted by suwind.                       "
  echo "---  Then supadmissing is run to (re)create the deleted traces.             "
  echo "---  Then header values and trace plot are displayed after supadmissing.    "
  echo "---  This makes it easy to tell that traces have been padded correctly.     "
  echo "                                                                            "
  echo "---  This test uses minval,maxval that are completely below input range.    "
  echo "---  Change this slightly to test completely above input range.             "
  echo "----------------------------------------------------------------------------"
#
  sugeomcsv rfile=CDPS.csv >tfake41.su create=all spikes=4,0.00,200,1000,500,0
#
  subfilt <tfake41.su >tfake42.su fpasshi=20
#
  suchw <tfake42.su >tfake43.su key1=gstat key2=cdp b=4
#
# sugethw <tfake43.su key=cdp,tracf,nhs,gstat,sx
#
  sustatic <tfake43.su >tfake44.su hdrs=1 sign=-1
#
  suxwigb <tfake44.su key=cdp title="input (plot by cdp key)" &
#
  suwind <tfake44.su >tfake45.su key=cdp reject=14,16,27
#
# So now you can run a bunch of tests similar to what you see next.
#
# supadmissing <tfake45.su >tfake46.su keyloc=cdp                   
  supadmissing <tfake45.su >tfake46.su              minval=2 maxval=5
#
  sugethw <tfake46.su key=cdp,tracf,nhs,gstat,sx
#
  suxwigb <tfake46.su key=cdp title="padded output (plot by cdp key)" &
#
