#!/bin/sh
# Sushiftcsv_test4 - for program SUSHIFTCSV
# Author: Andre Latour, Aug 2023
#
  echo "----------------------------------------------------------------------------"
  echo "---  Input fake traces, apply only source and receiver statics              "
  echo "----------------------------------------------------------------------------"
#
  sushiftcsv <fake02.su >fake41.su 
#
  suxwigb <fake41.su title=" applied only source and receiver statics " &
#
