#!/bin/sh
# Suprofcsv_test6 - for program SUPROFCSV
# Author: Andre Latour, Sept 2022
#
  echo "----------------------------------------------------------------------------"
  echo "---  Same as test 5, but then shift some parts of final profile.            "
  echo "---  (This is a test, to see WHY to do this, see demos/Geom3D/Sunearcsv).   "
  echo "----------------------------------------------------------------------------"
#
 suprofcsv keyx=gx keyy=gy keyp=asis gx=0,1000,1000 gy=0,0,1500 \
           chordi=10 nmaxa=30 nmaxs=30 chordf=10 \
           shiftrec=100,270,400 shiftdist=0,5,-3 \
           qout=testout61.csv
#
# Use sed to remove the first lines (C_SU header lines).
# Use cut with a deliminator of comma to retain only fields 3 and 4
# Use sed to replace every comma with a blank.               
# Use a2b to convert ascii to binary                        
# Use xgraph to plot points with marks of X, and no lines between.
#
  sed '/C_SU/d' testout61.csv >testout62.csv
  cut -d, -f3,4 <testout62.csv >testout63.csv
  sed '1,$ s/,/ /g' testout63.csv >testout63.txt
  a2b <testout63.txt >testout63.bin
  xgraph <testout63.bin n=999 linecolor=5 mark=5 marksize=5 linewidth=0 \
          width=800 height=800 x1beg=-100 x1end=1600 x2beg=-100 x2end=1600
#
