#!/bin/sh
# Suprofcsv_test5 - for program SUPROFCSV
# Author: Andre Latour, Sept 2022
#
  echo "----------------------------------------------------------------------------"
  echo "---  From 3, make points chord 10, average+smooth 30, final re-chord by 10. "
  echo "----------------------------------------------------------------------------"
#
 suprofcsv keyx=gx keyy=gy keyp=asis gx=0,1000,1000 gy=0,0,1500 \
           chordi=10 nmaxa=30 nmaxs=30 chordf=10 \
           qout=testout51.csv
#
# Use sed to remove the first lines (C_SU header lines).
# Use cut with a deliminator of comma to retain only fields 3 and 4
# Use sed to replace every comma with a blank.               
# Use a2b to convert ascii to binary                        
# Use xgraph to plot points with marks of X, and no lines between.
#
  sed '/C_SU/d' testout51.csv >testout52.csv
  cut -d, -f3,4 <testout52.csv >testout53.csv
  sed '1,$ s/,/ /g' testout53.csv >testout53.txt
  a2b <testout53.txt >testout53.bin
  xgraph <testout53.bin n=999 linecolor=5 mark=5 marksize=5 linewidth=0 \
          width=800 height=800 x1beg=-100 x1end=1600 x2beg=-100 x2end=1600
#
