#!/bin/sh
# Suprofcsv_test0 - for program SUPROFCSV
# Author: Andre Latour, Sept 2022
#
  echo "----------------------------------------------------------------------------"
  echo "---  Use parameters to make 3 locations (in a right angle).                 "
  echo "---  Most tests start with these 3 locations.                               "
  echo "----------------------------------------------------------------------------"
#
 suprofcsv keyx=gx keyy=gy keyp=asis gx=0,1000,1000 gy=0,0,1500 \
           chordi=0 nmaxa=0 nmaxs=0 chordf=0 \
           qout=testout01.csv
#
# Use sed to remove the first lines (C_SU header lines).
# Use cut with a deliminator of comma to retain only fields 3 and 4
# Use sed to replace every comma with a blank.               
# Use a2b to convert ascii to binary                        
# Use xgraph to plot points with marks of X, and no lines between.
#
  sed '/C_SU/d' testout01.csv >testout02.csv
  cut -d, -f3,4 <testout02.csv >testout03.csv
  sed '1,$ s/,/ /g' testout03.csv >testout03.txt
  a2b <testout03.txt >testout03.bin
  xgraph <testout03.bin n=3 linecolor=0 mark=1 marksize=15 linewidth=0 \
          width=800 height=800 x1beg=-100 x1end=1600 x2beg=-100 x2end=1600
#
