#!/bin/sh
# Suprofcsv_test1 - for program SUPROFCSV
# Author: Andre Latour, Sept 2022
#
  echo "----------------------------------------------------------------------------"
  echo "---  From 3 locations, create more points by chording in 10 metre intervals."
  echo "----------------------------------------------------------------------------"
#
 suprofcsv keyx=gx keyy=gy keyp=asis gx=0,1000,1000 gy=0,0,1500 \
           chordi=10 nmaxa=0 nmaxs=0 chordf=0 \
           qout=testout11.csv
#
# Use sed to remove the first lines (C_SU header lines).
# Use cut with a deliminator of comma to retain only fields 3 and 4
# Use sed to replace every comma with a blank.               
# Use a2b to convert ascii to binary                        
# Use xgraph to plot points with marks of X, and no lines between.
#
  sed '/C_SU/d' testout11.csv >testout12.csv
  cut -d, -f3,4 <testout12.csv >testout13.csv
  sed '1,$ s/,/ /g' testout13.csv >testout13.txt
  a2b <testout13.txt >testout13.bin
  xgraph <testout13.bin n=999 linecolor=0 mark=1 marksize=5 linewidth=0 \
          width=800 height=800 x1beg=-100 x1end=1600 x2beg=-100 x2end=1600
