#!/bin/sh
# Suflex2d_test6 - for program SUFLEX2D
# Author: Andre Latour, Nov  2022
#
  echo "----------------------------------------------------------------------------"
  echo "---  This test generates some traces in cdp,offset order.                   "
  echo "---  This is a test of binbest=1 (which uses the igc key values).           " 
  echo "---  (Also can change binbest and test other options).                      " 
  echo "----------------------------------------------------------------------------"
#
 sugeomcsv rfile=createcdps06.csv setid=m match=cdp,tracl names=c_su_id,cdp,tracl,ep,offset,igc >fakecdps06.su create=all spikes=4,0.01,200,1000,208,1200,500,-2000,800,1600,1000,0
#
 subfilt <fakecdps06.su >fakecdpsf06.su fpasshi=20
#
 sunmo <fakecdpsf06.su >fakecdpsfn06.su invert=1 cdp=1 tnmo=0,0.190,0.450,0.800 vnmo=800,1500,2000,3000
#
 suxwigb <fakecdpsfn06.su key=cdp x2beg=0 x2end=19 title="before suflex2d" & 
#
 suflex2d <fakecdpsfn06.su >fakecdpsfnf06.su binsize=50 binbest=1
#
 suxwigb <fakecdpsfnf06.su key=cdp x2beg=0 x2end=19 title="after suflex2d" &  
#
 sugethw <fakecdpsfnf06.su key=cdp,offset,igi,igc
#
